# BACKGROUND
background {
    monitor =
    path = ~/Pictures/Desktops/1 - Calvin & Hobbes.jpg  # supports png, jpg, webp (no animations, though)
    color = rgba(20, 36, 42, 0.5)
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = false
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 4
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = $foreground
    fade_on_empty = false
    rounding = -1
    check_color = rgb(204, 136, 34)
    placeholder_text = <i><span foreground="##cdd6f4">...</span></i>
    hide_input = true
    hide_input_base_color = rgb(235,235,245)
    position = 0, -200
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:6000] echo "$(date +"%A, %B %d")"
  color = rgba(255, 255, 255, 0.9)
  font_size = 42
  font_family = JetBrains Mono Extrabold

  position = 0, 340
  halign = center
  valign = center

  shadow_size = 15
  shadow_passes = 1
  shadow_color = rgba(0, 0, 0, 0.9)
  shadow_boost = 1.5
}

# TIME
label {
  monitor = 
  text = cmd[update:6000] echo "$(date +"%-I:%M")"
  color = rgba(255, 255, 255, 0.9)
  font_size = 95
  font_family = JetBrains Mono Extrabold

  position = 0, 200
  halign = center
  valign = center

  shadow_size = 15
  shadow_passes = 1
  shadow_color = rgba(0, 0, 0, 0.9)
}

# Keyboard
label {
  monitor = 
  text = cmd[update:1000] echo "$(if [[ `hyprctl devices | grep 'active keymap' | uniq | wc -l` -gt 1 ]] ; then echo 'Non-English Keyboard in Use'; fi)$(if [[ `cat /sys/class/leds/input0::capslock/brightness` == '1' ]]; then echo 'Capslock is ON'; fi)"
  color = rgba(255, 5, 5, 1)
  font_size = 25
  font_family = JetBrains Mono Extrabold

  position = 0, -300
  halign = center
  valign = center

  shadow_size = 15
  shadow_passes = 1
  shadow_color = rgba(0, 0, 0, 0.9)
}

# Battery State
label {
  monitor = 
  text = cmd[update:6000] echo "$(cat /sys/class/power_supply/BAT0/capacity)% $(cat /sys/class/power_supply/BAT0/status)"
  color = rgba(255, 255, 255, 0.9)
  font_size = 25
  font_family = JetBrains Mono Extrabold

  position = 0, -500
  halign = center
  valign = center

  shadow_size = 15
  shadow_passes = 1
  shadow_color = rgba(0, 0, 0, 0.9)
}
