##############################
### WINDOWS AND WORKSPACES ###
##############################

# Default in hyprland.conf

##############################
###         OTHERS         ###
##############################

# More Rules
windowrulev2 = bordercolor rgb(ff5555), xwayland:1 # check if window is xwayland

windowrule = float, class:pavucontrol
windowrule = float, class:pavucontrol-qt
windowrule = float, class:blueman-manager
windowrule = float, class:nm-connection-editor

# Browser Picture in Picture
windowrule = float, title:Picture-in-Picture
windowrule = pin, title:Picture-in-Picture
windowrule = move 69.5% 4%, title:Picture-in-Picture
