##############################
### WINDOWS AND WORKSPACES ###
##############################

# Default in hyprland.conf

##############################
###         OTHERS         ###
##############################

# More Rules
windowrule {
  name = Wayland-border
  border_color = rgb(ff5555)
  match:xwayland = 1 # check if window is xwayland
}

windowrule {
  name = pavucontrol-float
  float = on
  match:class = pavucontrol
}

windowrule {
  name = pavucontrol-qt-float
  float = on
  match:class = pavucontrol-qt
}

windowrule {
  name = blueman-manager-float
  float = on
  match:class = blueman-manager
}

windowrule {
  name = nm-connection-editor-float
  float = on
  match:class = nm-connection-editor
}

windowrule {
  name = Browser-Picture-in-Picture
  float = on
  pin = on
  move = ((monitor_w*0.695)) ((monitor_h*0.04))
  match:title = Picture-in-Picture
}
